/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tuning/tuning.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rovercom/tuning/tuning.pb-c.h"
void   protobuf_msgs__tuning_state__parameter__number_parameter__init
                     (ProtobufMsgs__TuningState__Parameter__NumberParameter         *message)
{
  static const ProtobufMsgs__TuningState__Parameter__NumberParameter init_value = PROTOBUF_MSGS__TUNING_STATE__PARAMETER__NUMBER_PARAMETER__INIT;
  *message = init_value;
}
void   protobuf_msgs__tuning_state__parameter__string_parameter__init
                     (ProtobufMsgs__TuningState__Parameter__StringParameter         *message)
{
  static const ProtobufMsgs__TuningState__Parameter__StringParameter init_value = PROTOBUF_MSGS__TUNING_STATE__PARAMETER__STRING_PARAMETER__INIT;
  *message = init_value;
}
void   protobuf_msgs__tuning_state__parameter__init
                     (ProtobufMsgs__TuningState__Parameter         *message)
{
  static const ProtobufMsgs__TuningState__Parameter init_value = PROTOBUF_MSGS__TUNING_STATE__PARAMETER__INIT;
  *message = init_value;
}
void   protobuf_msgs__tuning_state__init
                     (ProtobufMsgs__TuningState         *message)
{
  static const ProtobufMsgs__TuningState init_value = PROTOBUF_MSGS__TUNING_STATE__INIT;
  *message = init_value;
}
size_t protobuf_msgs__tuning_state__get_packed_size
                     (const ProtobufMsgs__TuningState *message)
{
  assert(message->base.descriptor == &protobuf_msgs__tuning_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__tuning_state__pack
                     (const ProtobufMsgs__TuningState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__tuning_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__tuning_state__pack_to_buffer
                     (const ProtobufMsgs__TuningState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__tuning_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__TuningState *
       protobuf_msgs__tuning_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__TuningState *)
     protobuf_c_message_unpack (&protobuf_msgs__tuning_state__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__tuning_state__free_unpacked
                     (ProtobufMsgs__TuningState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__tuning_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__tuning_state__parameter__number_parameter__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__TuningState__Parameter__NumberParameter, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__TuningState__Parameter__NumberParameter, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__tuning_state__parameter__number_parameter__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__tuning_state__parameter__number_parameter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__tuning_state__parameter__number_parameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.TuningState.Parameter.NumberParameter",
  "NumberParameter",
  "ProtobufMsgs__TuningState__Parameter__NumberParameter",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__TuningState__Parameter__NumberParameter),
  2,
  protobuf_msgs__tuning_state__parameter__number_parameter__field_descriptors,
  protobuf_msgs__tuning_state__parameter__number_parameter__field_indices_by_name,
  1,  protobuf_msgs__tuning_state__parameter__number_parameter__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__tuning_state__parameter__number_parameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__tuning_state__parameter__string_parameter__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__TuningState__Parameter__StringParameter, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__TuningState__Parameter__StringParameter, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__tuning_state__parameter__string_parameter__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange protobuf_msgs__tuning_state__parameter__string_parameter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__tuning_state__parameter__string_parameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.TuningState.Parameter.StringParameter",
  "StringParameter",
  "ProtobufMsgs__TuningState__Parameter__StringParameter",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__TuningState__Parameter__StringParameter),
  2,
  protobuf_msgs__tuning_state__parameter__string_parameter__field_descriptors,
  protobuf_msgs__tuning_state__parameter__string_parameter__field_indices_by_name,
  1,  protobuf_msgs__tuning_state__parameter__string_parameter__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__tuning_state__parameter__string_parameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__tuning_state__parameter__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__TuningState__Parameter, parameter_case),
    offsetof(ProtobufMsgs__TuningState__Parameter, number),
    &protobuf_msgs__tuning_state__parameter__number_parameter__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__TuningState__Parameter, parameter_case),
    offsetof(ProtobufMsgs__TuningState__Parameter, string),
    &protobuf_msgs__tuning_state__parameter__string_parameter__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__tuning_state__parameter__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = string */
};
static const ProtobufCIntRange protobuf_msgs__tuning_state__parameter__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__tuning_state__parameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.TuningState.Parameter",
  "Parameter",
  "ProtobufMsgs__TuningState__Parameter",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__TuningState__Parameter),
  2,
  protobuf_msgs__tuning_state__parameter__field_descriptors,
  protobuf_msgs__tuning_state__parameter__field_indices_by_name,
  2,  protobuf_msgs__tuning_state__parameter__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__tuning_state__parameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__tuning_state__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__TuningState, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dynamicParameters",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtobufMsgs__TuningState, n_dynamicparameters),
    offsetof(ProtobufMsgs__TuningState, dynamicparameters),
    &protobuf_msgs__tuning_state__parameter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__tuning_state__field_indices_by_name[] = {
  1,   /* field[1] = dynamicParameters */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange protobuf_msgs__tuning_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protobuf_msgs__tuning_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.TuningState",
  "TuningState",
  "ProtobufMsgs__TuningState",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__TuningState),
  2,
  protobuf_msgs__tuning_state__field_descriptors,
  protobuf_msgs__tuning_state__field_indices_by_name,
  1,  protobuf_msgs__tuning_state__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__tuning_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
