name: safe-controller
author: vu-ase
source: https://github.com/vu-ase/safe-controller
version: 1.0.0
description: This controller will make sure to stop in-front of an obstacle using the distance sensor

commands:
  build: make build
  run: ./bin/safe-controller


inputs:
  - service: imaging
    streams:
      - path
  - service: distance
    streams:
      - distance

as: controller

outputs:
  - decision

configuration:
  - name: speed
    tunable: true
    type: number
    value: 0.4
    mutable: true
  - name: kp
    tunable: true
    type: number
    value: 0.003
  - name: kd
    tunable: true
    type: number
    value: 0.00001
  - name: ki
    tunable: true
    type: number
    value: 0
  - name: desired-trajectory-point
    tunable: false
    type: number
    value: 320 # 640 / 2
  - name: brake-distance
    tunable: true
    type: number
    value: 1.0
