/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/imu.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rovercom/outputs/imu.pb-c.h"
void   protobuf_msgs__imu_sensor_output__vector__init
                     (ProtobufMsgs__ImuSensorOutput__Vector         *message)
{
  static const ProtobufMsgs__ImuSensorOutput__Vector init_value = PROTOBUF_MSGS__IMU_SENSOR_OUTPUT__VECTOR__INIT;
  *message = init_value;
}
void   protobuf_msgs__imu_sensor_output__init
                     (ProtobufMsgs__ImuSensorOutput         *message)
{
  static const ProtobufMsgs__ImuSensorOutput init_value = PROTOBUF_MSGS__IMU_SENSOR_OUTPUT__INIT;
  *message = init_value;
}
size_t protobuf_msgs__imu_sensor_output__get_packed_size
                     (const ProtobufMsgs__ImuSensorOutput *message)
{
  assert(message->base.descriptor == &protobuf_msgs__imu_sensor_output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protobuf_msgs__imu_sensor_output__pack
                     (const ProtobufMsgs__ImuSensorOutput *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protobuf_msgs__imu_sensor_output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protobuf_msgs__imu_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__ImuSensorOutput *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protobuf_msgs__imu_sensor_output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtobufMsgs__ImuSensorOutput *
       protobuf_msgs__imu_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtobufMsgs__ImuSensorOutput *)
     protobuf_c_message_unpack (&protobuf_msgs__imu_sensor_output__descriptor,
                                allocator, len, data);
}
void   protobuf_msgs__imu_sensor_output__free_unpacked
                     (ProtobufMsgs__ImuSensorOutput *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protobuf_msgs__imu_sensor_output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protobuf_msgs__imu_sensor_output__vector__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput__Vector, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput__Vector, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput__Vector, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__imu_sensor_output__vector__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange protobuf_msgs__imu_sensor_output__vector__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protobuf_msgs__imu_sensor_output__vector__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.ImuSensorOutput.Vector",
  "Vector",
  "ProtobufMsgs__ImuSensorOutput__Vector",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__ImuSensorOutput__Vector),
  3,
  protobuf_msgs__imu_sensor_output__vector__field_descriptors,
  protobuf_msgs__imu_sensor_output__vector__field_indices_by_name,
  1,  protobuf_msgs__imu_sensor_output__vector__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__imu_sensor_output__vector__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protobuf_msgs__imu_sensor_output__field_descriptors[8] =
{
  {
    "temperature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "magnetometer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, magnetometer),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyroscope",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, gyroscope),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "euler",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, euler),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accelerometer",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, accelerometer),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linearAccelerometer",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, linearaccelerometer),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, velocity),
    &protobuf_msgs__imu_sensor_output__vector__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ProtobufMsgs__ImuSensorOutput, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protobuf_msgs__imu_sensor_output__field_indices_by_name[] = {
  4,   /* field[4] = accelerometer */
  3,   /* field[3] = euler */
  2,   /* field[2] = gyroscope */
  5,   /* field[5] = linearAccelerometer */
  1,   /* field[1] = magnetometer */
  7,   /* field[7] = speed */
  0,   /* field[0] = temperature */
  6,   /* field[6] = velocity */
};
static const ProtobufCIntRange protobuf_msgs__imu_sensor_output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor protobuf_msgs__imu_sensor_output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "protobuf_msgs.ImuSensorOutput",
  "ImuSensorOutput",
  "ProtobufMsgs__ImuSensorOutput",
  "protobuf_msgs",
  sizeof(ProtobufMsgs__ImuSensorOutput),
  8,
  protobuf_msgs__imu_sensor_output__field_descriptors,
  protobuf_msgs__imu_sensor_output__field_indices_by_name,
  1,  protobuf_msgs__imu_sensor_output__number_ranges,
  (ProtobufCMessageInit) protobuf_msgs__imu_sensor_output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
