/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/imu.proto */

#ifndef PROTOBUF_C_outputs_2fimu_2eproto__INCLUDED
#define PROTOBUF_C_outputs_2fimu_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__ImuSensorOutput ProtobufMsgs__ImuSensorOutput;
typedef struct _ProtobufMsgs__ImuSensorOutput__Vector ProtobufMsgs__ImuSensorOutput__Vector;


/* --- enums --- */


/* --- messages --- */

struct  _ProtobufMsgs__ImuSensorOutput__Vector
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define PROTOBUF_MSGS__IMU_SENSOR_OUTPUT__VECTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__imu_sensor_output__vector__descriptor) \
    , 0, 0, 0 }


struct  _ProtobufMsgs__ImuSensorOutput
{
  ProtobufCMessage base;
  int32_t temperature;
  ProtobufMsgs__ImuSensorOutput__Vector *magnetometer;
  ProtobufMsgs__ImuSensorOutput__Vector *gyroscope;
  ProtobufMsgs__ImuSensorOutput__Vector *euler;
  ProtobufMsgs__ImuSensorOutput__Vector *accelerometer;
  ProtobufMsgs__ImuSensorOutput__Vector *linearaccelerometer;
  ProtobufMsgs__ImuSensorOutput__Vector *velocity;
  float speed;
};
#define PROTOBUF_MSGS__IMU_SENSOR_OUTPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__imu_sensor_output__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, 0 }


/* ProtobufMsgs__ImuSensorOutput__Vector methods */
void   protobuf_msgs__imu_sensor_output__vector__init
                     (ProtobufMsgs__ImuSensorOutput__Vector         *message);
/* ProtobufMsgs__ImuSensorOutput methods */
void   protobuf_msgs__imu_sensor_output__init
                     (ProtobufMsgs__ImuSensorOutput         *message);
size_t protobuf_msgs__imu_sensor_output__get_packed_size
                     (const ProtobufMsgs__ImuSensorOutput   *message);
size_t protobuf_msgs__imu_sensor_output__pack
                     (const ProtobufMsgs__ImuSensorOutput   *message,
                      uint8_t             *out);
size_t protobuf_msgs__imu_sensor_output__pack_to_buffer
                     (const ProtobufMsgs__ImuSensorOutput   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__ImuSensorOutput *
       protobuf_msgs__imu_sensor_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__imu_sensor_output__free_unpacked
                     (ProtobufMsgs__ImuSensorOutput *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__ImuSensorOutput__Vector_Closure)
                 (const ProtobufMsgs__ImuSensorOutput__Vector *message,
                  void *closure_data);
typedef void (*ProtobufMsgs__ImuSensorOutput_Closure)
                 (const ProtobufMsgs__ImuSensorOutput *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protobuf_msgs__imu_sensor_output__descriptor;
extern const ProtobufCMessageDescriptor protobuf_msgs__imu_sensor_output__vector__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_outputs_2fimu_2eproto__INCLUDED */
