/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: outputs/laptime.proto */

#ifndef PROTOBUF_C_outputs_2flaptime_2eproto__INCLUDED
#define PROTOBUF_C_outputs_2flaptime_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ProtobufMsgs__LapTimeOutput ProtobufMsgs__LapTimeOutput;


/* --- enums --- */


/* --- messages --- */

struct  _ProtobufMsgs__LapTimeOutput
{
  ProtobufCMessage base;
  /*
   * Time of complete lap in ms
   */
  uint64_t laptime;
  /*
   * Start of the lap
   */
  uint64_t lapstarttime;
};
#define PROTOBUF_MSGS__LAP_TIME_OUTPUT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protobuf_msgs__lap_time_output__descriptor) \
    , 0, 0 }


/* ProtobufMsgs__LapTimeOutput methods */
void   protobuf_msgs__lap_time_output__init
                     (ProtobufMsgs__LapTimeOutput         *message);
size_t protobuf_msgs__lap_time_output__get_packed_size
                     (const ProtobufMsgs__LapTimeOutput   *message);
size_t protobuf_msgs__lap_time_output__pack
                     (const ProtobufMsgs__LapTimeOutput   *message,
                      uint8_t             *out);
size_t protobuf_msgs__lap_time_output__pack_to_buffer
                     (const ProtobufMsgs__LapTimeOutput   *message,
                      ProtobufCBuffer     *buffer);
ProtobufMsgs__LapTimeOutput *
       protobuf_msgs__lap_time_output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protobuf_msgs__lap_time_output__free_unpacked
                     (ProtobufMsgs__LapTimeOutput *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtobufMsgs__LapTimeOutput_Closure)
                 (const ProtobufMsgs__LapTimeOutput *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protobuf_msgs__lap_time_output__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_outputs_2flaptime_2eproto__INCLUDED */
